# Generated by Django 5.2.14 on 2026-05-23 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DavetTalebi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.CharField(max_length=100, verbose_name='Ad Soyad')),
                ('telefon', models.CharField(max_length=20, verbose_name='Telefon')),
                ('organizasyon_turu', models.CharField(choices=[('dogum_gunu', 'Doğum Günü'), ('evlilik_teklifi', 'Evlilik Teklifi'), ('grup_masasi', 'Grup Masası'), ('ozel_kutlama', 'Özel Kutlama'), ('diger', 'Diğer')], max_length=30, verbose_name='Organizasyon Türü')),
                ('tarih', models.DateField(verbose_name='Tarih')),
                ('saat_araligi', models.CharField(blank=True, max_length=50, null=True, verbose_name='Saat Aralığı')),
                ('kisi_sayisi', models.IntegerField(blank=True, null=True, verbose_name='Kişi Sayısı')),
                ('alan_tercihi', models.CharField(blank=True, choices=[('ic_alan', 'İç Alan'), ('acik_alan', 'Açık Alan'), ('fark_etmez', 'Fark Etmez')], max_length=20, null=True, verbose_name='Alan Tercihi')),
                ('notlar', models.TextField(blank=True, null=True, verbose_name='Notlar / Özel İstek')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Talep Tarihi')),
            ],
            options={
                'verbose_name': 'Davet Talebi',
                'verbose_name_plural': 'Davet Talepleri',
            },
        ),
    ]
